# This is a basic workflow to help you get started with Actions

name: Generate OpenApi static HTML2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: OpenAPI Generator Action
        uses: kpurdon/openapi-generator-action@v0.0.3
        with:
          args: "generate -i $GITHUB_WORKSPACE/PenAndPaperDmHelperSpec.yaml -g html2 -o $GITHUB_WORKSPACE/public"
      
     
      - name: Git Commit and Push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'Generate static HTML2 for OpenApi spec'
          force-add: 'true'
          files: $GITHUB_WORKSPACE/public
 
